#!/usr/bin/env bash

origin_url=$(git config --get remote.origin.url)

if [ "$origin_url" != "git://github.com/v8/v8.git" ]; then
  echo "Not in a V8 repository!";
  exit 1;
fi

branch_name=$1

if [ "$#" -lt 2 ]; then
  echo "Enter new feature-branch name:"
  read branch_name
fi

git checkout origin/master -f -B master
git pull --rebase origin master
git checkout -B "$branch_name"

